language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

services:
  - mysql

env:
  - COMPOSER_FLAGS="--prefer-stable"

php:
  - hhvm

matrix:
  include:
    # highest and lowest php with minimal dependencies
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"

    # also run default with 3.0
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*"

    # highest and lowest php with the latest symfony versions
    - php: 5.5
      env: SYMFONY_VERSION="3.1.*"
    - php: 7.0
      env: SYMFONY_VERSION="3.1.*"

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
